select
    id as return_id,
    returnNumber as return_number,
    orderId as order_id,
    status,
    reason,
    currency,
    createdAt as created_at,
    updatedAt as updated_at,
    approvedAt as approved_at,
    rejectedAt as rejected_at,
    cancelledAt as cancelled_at,
    cast(refund.subtotalMinor as numeric) / 100 as refund_subtotal_amount,
    refund.restockingFeeRate as refund_restocking_fee_rate,
    cast(refund.restockingFeeMinor as numeric) / 100 as refund_restocking_fee_amount,
    cast(refund.estimatedMinor as numeric) / 100 as refund_estimated_amount,
    cast(refund.refundedMinor as numeric) / 100 as refund_refunded_amount,
    refund.refundedAt as refund_refunded_at,
    reverseShipment.status as reverse_shipment_status,
    reverseShipment.trackingNumber as reverse_shipment_tracking_number,
    reverseShipment.trackingUrl as reverse_shipment_tracking_url,
    reverseShipment.shippedAt as reverse_shipment_shipped_at,
    reverseShipment.receivedAt as reverse_shipment_received_at
from {{ source('raw', 'returns') }}
